### ISSUE TITLE
What is the problem with homebrew-core/llvm

### ISSUE THREAD

**Issue by zmactep** [llvm-hs/homebrew-llvm#2]
Why should we have an additional llvm package, what is the problem with default homebrew llvm? Maybe it is possible to add one more flag if it is required?

**Comment by tmcdonell** [comment]
You are free to use the homebrew `llvm.rb` package if you wish. That should, probably, also work (though I have not tried it in a while).

The difference is that these ones are versioned formula, so you'll get all the executables named `llc-4.0`, `clang-4.0` etc linked into `homebrew_prefix/bin`. The homebrew `llvm.rb` on the other hand is a `keg_only`, so you'll need to update your `PATH` to include wherever it was installed, or otherwise. The versioned formula are particularly useful if you want to install multiple versions side-by-side.

Also;

 - Last I heard, homebrew is planning to do away with flags entirely, as it is difficult for them to test these with CI.

 - As far as I can tell, homebrew is preferring to support only the latest version of a package, [as described here](http://docs.brew.sh/Versions.html). The recommendation instead is if you want to support multiple / custom versions, [create your own tap](http://docs.brew.sh/How-to-Create-and-Maintain-a-Tap.html) (which is what we've done).

 - When the `llvm.rb` formula was updated from 3.9 to 4.0 recently, this broke things for a lot of people. I've also run into this problem in the past with the renaming and then removal of `llvm35.rb`, for example. In anticipation of this happening to us in the future, I created these.

So yes, you are correct, these may not be 100% necessary, but from my past experience I think having this stable option available, especially since we can make sure it works with whatever `llvm-hs` and ghc require, is a good idea.

**Comment by zmactep** [comment]
Hi, @tmcdonell !

Thank you for the answer. So, it is not a "special" version, but just a versioned one for consistent naming.

BTW, `homebrew-core/llvm` formula does not work for me without additional manipulations, as it handles an error on `llvm-hs` build:
```
dyld: Library not loaded: @rpath/libLLVMLTO.dylib
  Referenced from: /private/var/folders/pj/q3hm9_nn5jj5nvr82zkyhg3r0000gn/T/stack45213/llvm-hs-4.0.0.0/.stack-work/dist/x86_64-osx/Cabal-1.24.2.0/build/LLVM/Internal/LibraryFunction_hsc_make
  Reason: image not found
```

As I understand it may be fixed with `install_name_tool` as described in this formula.

**Comment by tmcdonell** [comment]
Correct. It's not really special, but I find it useful to have around, and others might as well.

Yes, `install_name_tool` would fix that. The `@rpath` bit would usually be substituted for entries in `DYLD_LIBRARY_PATH`, but because of system integrity protection and the way ghci is set up, we don't get access to `DYLD_LIBRARY_PATH`. So, it's easier to just replace the DYLIB entries with absolute paths.
